//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace newmodel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class newentities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new newentities object using the connection string found in the 'newentities' section of the application configuration file.
        /// </summary>
        public newentities() : base("name=newentities", "newentities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new newentities object.
        /// </summary>
        public newentities(string connectionString) : base(connectionString, "newentities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new newentities object.
        /// </summary>
        public newentities(EntityConnection connection) : base(connection, "newentities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<feedback> feedbacks
        {
            get
            {
                if ((_feedbacks == null))
                {
                    _feedbacks = base.CreateObjectSet<feedback>("feedbacks");
                }
                return _feedbacks;
            }
        }
        private ObjectSet<feedback> _feedbacks;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the feedbacks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofeedbacks(feedback feedback)
        {
            base.AddObject("feedbacks", feedback);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="newmodel", Name="feedback")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class feedback : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new feedback object.
        /// </summary>
        /// <param name="department">Initial value of the department property.</param>
        /// <param name="empno">Initial value of the empno property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="email_id">Initial value of the Email_id property.</param>
        /// <param name="landline">Initial value of the landline property.</param>
        /// <param name="cell">Initial value of the cell property.</param>
        /// <param name="q1">Initial value of the q1 property.</param>
        /// <param name="q2">Initial value of the q2 property.</param>
        /// <param name="q3">Initial value of the q3 property.</param>
        /// <param name="q4">Initial value of the q4 property.</param>
        /// <param name="q5">Initial value of the q5 property.</param>
        /// <param name="q6">Initial value of the q6 property.</param>
        /// <param name="q7">Initial value of the q7 property.</param>
        /// <param name="q8">Initial value of the q8 property.</param>
        /// <param name="q9">Initial value of the q9 property.</param>
        /// <param name="q10">Initial value of the q10 property.</param>
        /// <param name="q11">Initial value of the q11 property.</param>
        /// <param name="q12">Initial value of the q12 property.</param>
        /// <param name="suggestions">Initial value of the suggestions property.</param>
        /// <param name="besttechno">Initial value of the besttechno property.</param>
        public static feedback Createfeedback(global::System.String department, global::System.Decimal empno, global::System.String name, global::System.String email_id, global::System.Decimal landline, global::System.Decimal cell, global::System.Decimal q1, global::System.Decimal q2, global::System.Decimal q3, global::System.Decimal q4, global::System.Decimal q5, global::System.Decimal q6, global::System.Decimal q7, global::System.Decimal q8, global::System.Decimal q9, global::System.Decimal q10, global::System.Decimal q11, global::System.Decimal q12, global::System.String suggestions, global::System.String besttechno)
        {
            feedback feedback = new feedback();
            feedback.department = department;
            feedback.empno = empno;
            feedback.name = name;
            feedback.Email_id = email_id;
            feedback.landline = landline;
            feedback.cell = cell;
            feedback.q1 = q1;
            feedback.q2 = q2;
            feedback.q3 = q3;
            feedback.q4 = q4;
            feedback.q5 = q5;
            feedback.q6 = q6;
            feedback.q7 = q7;
            feedback.q8 = q8;
            feedback.q9 = q9;
            feedback.q10 = q10;
            feedback.q11 = q11;
            feedback.q12 = q12;
            feedback.suggestions = suggestions;
            feedback.besttechno = besttechno;
            return feedback;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String department
        {
            get
            {
                return _department;
            }
            set
            {
                OndepartmentChanging(value);
                ReportPropertyChanging("department");
                _department = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("department");
                OndepartmentChanged();
            }
        }
        private global::System.String _department;
        partial void OndepartmentChanging(global::System.String value);
        partial void OndepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal empno
        {
            get
            {
                return _empno;
            }
            set
            {
                if (_empno != value)
                {
                    OnempnoChanging(value);
                    ReportPropertyChanging("empno");
                    _empno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("empno");
                    OnempnoChanged();
                }
            }
        }
        private global::System.Decimal _empno;
        partial void OnempnoChanging(global::System.Decimal value);
        partial void OnempnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email_id
        {
            get
            {
                return _Email_id;
            }
            set
            {
                OnEmail_idChanging(value);
                ReportPropertyChanging("Email_id");
                _Email_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email_id");
                OnEmail_idChanged();
            }
        }
        private global::System.String _Email_id;
        partial void OnEmail_idChanging(global::System.String value);
        partial void OnEmail_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal landline
        {
            get
            {
                return _landline;
            }
            set
            {
                OnlandlineChanging(value);
                ReportPropertyChanging("landline");
                _landline = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("landline");
                OnlandlineChanged();
            }
        }
        private global::System.Decimal _landline;
        partial void OnlandlineChanging(global::System.Decimal value);
        partial void OnlandlineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cell
        {
            get
            {
                return _cell;
            }
            set
            {
                OncellChanging(value);
                ReportPropertyChanging("cell");
                _cell = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cell");
                OncellChanged();
            }
        }
        private global::System.Decimal _cell;
        partial void OncellChanging(global::System.Decimal value);
        partial void OncellChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal q1
        {
            get
            {
                return _q1;
            }
            set
            {
                Onq1Changing(value);
                ReportPropertyChanging("q1");
                _q1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("q1");
                Onq1Changed();
            }
        }
        private global::System.Decimal _q1;
        partial void Onq1Changing(global::System.Decimal value);
        partial void Onq1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal q2
        {
            get
            {
                return _q2;
            }
            set
            {
                Onq2Changing(value);
                ReportPropertyChanging("q2");
                _q2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("q2");
                Onq2Changed();
            }
        }
        private global::System.Decimal _q2;
        partial void Onq2Changing(global::System.Decimal value);
        partial void Onq2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal q3
        {
            get
            {
                return _q3;
            }
            set
            {
                Onq3Changing(value);
                ReportPropertyChanging("q3");
                _q3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("q3");
                Onq3Changed();
            }
        }
        private global::System.Decimal _q3;
        partial void Onq3Changing(global::System.Decimal value);
        partial void Onq3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal q4
        {
            get
            {
                return _q4;
            }
            set
            {
                Onq4Changing(value);
                ReportPropertyChanging("q4");
                _q4 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("q4");
                Onq4Changed();
            }
        }
        private global::System.Decimal _q4;
        partial void Onq4Changing(global::System.Decimal value);
        partial void Onq4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal q5
        {
            get
            {
                return _q5;
            }
            set
            {
                Onq5Changing(value);
                ReportPropertyChanging("q5");
                _q5 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("q5");
                Onq5Changed();
            }
        }
        private global::System.Decimal _q5;
        partial void Onq5Changing(global::System.Decimal value);
        partial void Onq5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal q6
        {
            get
            {
                return _q6;
            }
            set
            {
                Onq6Changing(value);
                ReportPropertyChanging("q6");
                _q6 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("q6");
                Onq6Changed();
            }
        }
        private global::System.Decimal _q6;
        partial void Onq6Changing(global::System.Decimal value);
        partial void Onq6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal q7
        {
            get
            {
                return _q7;
            }
            set
            {
                Onq7Changing(value);
                ReportPropertyChanging("q7");
                _q7 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("q7");
                Onq7Changed();
            }
        }
        private global::System.Decimal _q7;
        partial void Onq7Changing(global::System.Decimal value);
        partial void Onq7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal q8
        {
            get
            {
                return _q8;
            }
            set
            {
                Onq8Changing(value);
                ReportPropertyChanging("q8");
                _q8 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("q8");
                Onq8Changed();
            }
        }
        private global::System.Decimal _q8;
        partial void Onq8Changing(global::System.Decimal value);
        partial void Onq8Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal q9
        {
            get
            {
                return _q9;
            }
            set
            {
                Onq9Changing(value);
                ReportPropertyChanging("q9");
                _q9 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("q9");
                Onq9Changed();
            }
        }
        private global::System.Decimal _q9;
        partial void Onq9Changing(global::System.Decimal value);
        partial void Onq9Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal q10
        {
            get
            {
                return _q10;
            }
            set
            {
                Onq10Changing(value);
                ReportPropertyChanging("q10");
                _q10 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("q10");
                Onq10Changed();
            }
        }
        private global::System.Decimal _q10;
        partial void Onq10Changing(global::System.Decimal value);
        partial void Onq10Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal q11
        {
            get
            {
                return _q11;
            }
            set
            {
                Onq11Changing(value);
                ReportPropertyChanging("q11");
                _q11 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("q11");
                Onq11Changed();
            }
        }
        private global::System.Decimal _q11;
        partial void Onq11Changing(global::System.Decimal value);
        partial void Onq11Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal q12
        {
            get
            {
                return _q12;
            }
            set
            {
                Onq12Changing(value);
                ReportPropertyChanging("q12");
                _q12 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("q12");
                Onq12Changed();
            }
        }
        private global::System.Decimal _q12;
        partial void Onq12Changing(global::System.Decimal value);
        partial void Onq12Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String suggestions
        {
            get
            {
                return _suggestions;
            }
            set
            {
                OnsuggestionsChanging(value);
                ReportPropertyChanging("suggestions");
                _suggestions = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("suggestions");
                OnsuggestionsChanged();
            }
        }
        private global::System.String _suggestions;
        partial void OnsuggestionsChanging(global::System.String value);
        partial void OnsuggestionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String besttechno
        {
            get
            {
                return _besttechno;
            }
            set
            {
                OnbesttechnoChanging(value);
                ReportPropertyChanging("besttechno");
                _besttechno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("besttechno");
                OnbesttechnoChanged();
            }
        }
        private global::System.String _besttechno;
        partial void OnbesttechnoChanging(global::System.String value);
        partial void OnbesttechnoChanged();

        #endregion
    
    }

    #endregion
    
}
